.PHONY: build clean

clean:
	rm -rf ./functions

build:
	mkdir -p functions
	# getOneUser
	go get ./srv/endpoints/users/getone/...
	go build -o functions/users/getone ./srv/endpoints/users/getone/...
	# getAllWeights
	go get ./srv/endpoints/weights/getall/...
	go build -o functions/weights/getall ./srv/endpoints/weights/getall/...
